"""
Shared HTML report generator for performance summaries.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict


def generate_html_report(
    benchmarks: Dict[str, Any],
    hw_caps: Dict[str, Any],
    bottlenecks: Dict[str, Any],
    score: Dict[str, Any],
    cost: Dict[str, Any],
    efficiency: Dict[str, Any],
) -> str:
    """Generate a lightweight HTML report summarizing performance data."""
    gpu_name = hw_caps.get("gpu", {}).get("name", "Unknown GPU")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    html_parts = [
        "<!DOCTYPE html>",
        "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        f"<title>GPU Performance Report - {gpu_name}</title>",
        "<style>",
        ":root{--bg:#0f0f14;--card:#1a1a24;--text:#fff;--muted:#a0a0b0;--success:#22c55e;--warn:#f59e0b;--danger:#ef4444;--primary:#8854d0;}",
        "*{margin:0;padding:0;box-sizing:border-box;} body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--bg);color:var(--text);padding:2rem;line-height:1.6;}",
        ".container{max-width:1200px;margin:0 auto;} .header{text-align:center;margin-bottom:2rem;padding:2rem;background:linear-gradient(135deg,rgba(136,84,208,.2),rgba(59,130,246,.2));border-radius:16px;}",
        ".header h1{font-size:2.5rem;margin-bottom:.5rem;} .header .subtitle{color:var(--muted);} .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem;margin-bottom:2rem;}",
        ".card{background:var(--card);padding:1.25rem;border-radius:12px;margin-bottom:1rem;} .stat{font-size:2rem;font-weight:700;color:var(--success);} .label{color:var(--muted);font-size:.9rem;}",
        "table{width:100%;border-collapse:collapse;} th,td{padding:.75rem;text-align:left;border-bottom:1px solid rgba(255,255,255,.1);} th{color:var(--muted);font-weight:500;}",
        ".badge{display:inline-block;padding:.25rem .75rem;border-radius:4px;font-size:.85rem;font-weight:600;} .badge-success{background:rgba(34,197,94,.2);color:var(--success);} .badge-warning{background:rgba(245,158,11,.2);color:var(--warn);} .badge-danger{background:rgba(239,68,68,.2);color:var(--danger);}",
        ".footer{text-align:center;color:var(--muted);margin-top:3rem;padding-top:2rem;border-top:1px solid rgba(255,255,255,.1);font-size:.9rem;}",
        "</style></head><body><div class='container'>",
        "<div class='header'>",
        "<h1>🚀 GPU Performance Report</h1>",
        f"<p class='subtitle'>{gpu_name} | Generated {timestamp}</p>",
        "</div>",
        "<div class='grid'>",
        f"<div class='card'><div class='stat'>{score.get('score',0)}/100</div><div class='label'>Optimization Score</div></div>",
        f"<div class='card'><div class='stat'>{len(benchmarks.get('benchmarks',[]))}</div><div class='label'>Benchmarks</div></div>",
        f"<div class='card'><div class='stat'>{efficiency.get('overall',{}).get('avg_flops_efficiency',0):.0f}%</div><div class='label'>Avg FLOPS Efficiency</div></div>",
        f"<div class='card'><div class='stat'>${cost.get('summary',{}).get('total_savings',0):.2f}</div><div class='label'>Cost Savings/M ops</div></div>",
        "</div>",
        "<div class='card'><h2>📊 Top Benchmarks</h2><table><thead><tr><th>Benchmark</th><th>Baseline</th><th>Optimized</th><th>Speedup</th></tr></thead><tbody>",
    ]

    for b in benchmarks.get("benchmarks", [])[:10]:
        speedup = b.get("speedup", 1.0)
        badge = "success" if speedup >= 1.5 else "warning" if speedup >= 1.1 else "danger"
        html_parts.append(
            f"<tr><td>{b.get('name','Unknown')[:40]}</td><td>{b.get('baseline_time_ms',0):.2f} ms</td>"
            f"<td>{b.get('optimized_time_ms',0):.2f} ms</td><td><span class='badge badge-{badge}'>{speedup:.2f}x</span></td></tr>"
        )

    html_parts.append("</tbody></table></div>")

    html_parts.append("<div class='card'><h2>🚨 Detected Bottlenecks</h2>")
    for bn in bottlenecks.get("bottlenecks", [])[:5]:
        severity_class = "danger" if bn.get("severity") == "high" else "warning"
        html_parts.append(
            f"<div style='margin-bottom:.75rem;'><div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:.35rem;'>"
            f"<strong>{bn.get('type','').replace('_',' ').title()}</strong>"
            f"<span class='badge badge-{severity_class}'>{bn.get('percentage',0):.1f}%</span></div>"
            f"<p style='color:var(--muted);'>{bn.get('description','')}</p></div>"
        )
    html_parts.append("</div>")

    html_parts.append(
        f"<div class='footer'><p>Generated by GPU Performance Lab Dashboard</p>"
        f"<p style='margin-top:.5rem;'>Hardware: {gpu_name} | Architecture: {hw_caps.get('architecture','unknown')}</p></div>"
    )

    html_parts.append("</div></body></html>")
    return "\n".join(html_parts)

